### ISSUE TITLE
Curious about ping delay/baked simulation/impact

### ISSUE THREAD

**Issue by Xortrox** [ryanjpwatts/esp-analysis#1]
Saw this and figured I'd make an issue discussing it.

To some extent I believe Valve tries to do something similar in CS:GO at least historically (maybe CS2 also)

But I figure to some extent they might be "baking occlusion areas" too big for accuracy, such as the image where players are near but behind the door?

Part of the issue/reason they seem to be doing it poorly, might be more visible in unity if you try with various different latency settings, assuming mirror has what unity's netcode default transport has, where you can set a "ping to simulate" with

Also do you figure they bake "occlusion cells" around the world rather than going for your example approach that uses raycasts?

I imagine it a bit similar to how unity does "[occlusion culling](https://docs.unity3d.com/Manual/OcclusionCulling.html)", which won't result in an extremely accurate result I believe (such as near that door)

**Comment by ryanjpwatts** [comment]
Yes, they have definitely tried and seemingly succeeded before. 

During my research I came across [this](https://www.reddit.com/r/GlobalOffensive/comments/35zwwy/optional_counterstrike_global_offensive_update/) which suggests Valve were taking similar steps to prevent it and players claimed it worked with great results but footage of functional cross-map ESPs in CS2 seem to paint a different picture unfortunately, even in competitive matchmaking.

I would definitely expect Valve to consider the approach of baked occlusion culling data as they all have static, unchanging maps. It would likely be a lot more performant but effectiveness could be questionable for the reason you proposed with these baked areas potentially being too large. My solution aimed to support changing world environments like you would see in games like Fortnite, Rust and Overwatch.

I did some expirementing with latency (as yes, mirror does thankfully provide latency simulation) and and the results weren't too different with 100ms, regardless this could be alleviated by sending rays to positions ahead of where the player may move, a technique already done in a lot of server-authorative movement systems where the clients player will move on their screen based on the inputs provided despite the server being the true assigner of position.

Factoring in the requirement to network the position of both player and player camera I may compare the performance between engine camera culling techniques and my raycast approach, it would be good to see in numbers how both solutions could affect a server.
